---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app.kubernetes.io/name: vdbench-test
  name: vdbench-test
spec:
  output:
    to:
      kind: ImageStreamTag
      name: vdbench-test:latest
  source:
    # Expect a local directory to be streamed to OpenShift as a build source
    type: Git
    git: 
      uri: https://github.com/Shawn-Houston/vdbench-test.git
  strategy:
    type: Docker
    dockerStrategy:
      # Find the image build instructions in ./Dockerfile
      dockerfilePath: Containerfile
  triggers:
  - type: ImageChange
  - type: ConfigChange
...
